---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	safety_guard(safety_guard)
	route_record(route_record)
	redirect(redirect)
	guard_answer(guard_answer<hr/><small><em>__interrupt = before</em></small>)
	route_intent(route_intent)
	handle_object(handle_object)
	rephrase(rephrase)
	empathy(empathy)
	clarify(clarify)
	absorb(absorb<hr/><small><em>__interrupt = before</em></small>)
	read_record(read_record)
	acknowledge(acknowledge)
	socratic_q(socratic_q)
	evaluate(evaluate)
	praise(praise)
	reflect(reflect)
	capture_insight(capture_insight<hr/><small><em>__interrupt = before</em></small>)
	hint(hint)
	reveal(reveal)
	closing(closing)
	enrich_agent(enrich_agent)
	tools(tools)
	__end__([<p>__end__</p>]):::last
	__start__ --> safety_guard;
	absorb -.-> __end__;
	absorb -.-> read_record;
	capture_insight -.-> __end__;
	capture_insight -.-> enrich_agent;
	clarify --> absorb;
	empathy -. &nbsp;vague&nbsp; .-> clarify;
	empathy -. &nbsp;ok&nbsp; .-> read_record;
	enrich_agent -. &nbsp;__end__&nbsp; .-> closing;
	enrich_agent -.-> tools;
	evaluate -.-> hint;
	evaluate -. &nbsp;correct&nbsp; .-> praise;
	evaluate -.-> reveal;
	guard_answer -.-> __end__;
	guard_answer -.-> route_intent;
	handle_object --> absorb;
	hint --> guard_answer;
	praise --> reflect;
	read_record -. &nbsp;skip&nbsp; .-> acknowledge;
	read_record -. &nbsp;teach&nbsp; .-> socratic_q;
	reflect --> capture_insight;
	rephrase --> guard_answer;
	reveal --> reflect;
	route_intent -. &nbsp;stop&nbsp; .-> closing;
	route_intent -. &nbsp;answer&nbsp; .-> evaluate;
	route_intent -. &nbsp;object&nbsp; .-> handle_object;
	route_intent -. &nbsp;confused&nbsp; .-> rephrase;
	route_record -. &nbsp;record&nbsp; .-> empathy;
	route_record -. &nbsp;not_record&nbsp; .-> redirect;
	safety_guard -.-> __end__;
	safety_guard -.-> route_record;
	socratic_q --> guard_answer;
	tools --> enrich_agent;
	acknowledge --> __end__;
	closing --> __end__;
	redirect --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
